# Generated by Django 2.2.10 on 2020-02-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucketdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Bucket',
        ),
    ]
